pipelines:
  branches:
    dev:
      - step:
          name: trigger_manual
          script:
            - echo "Trigger manually if needed"

      - step:
          name: dev_sonar
          trigger: manual
          image: node:18
          script:
            - pipe: sonarsource/sonarqube-scan:1.1.0
              variables:
                SONAR_HOST_URL: ${SONAR_HOST_URL}
                SONAR_TOKEN: ${SONAR_TOKEN}

      - step:
          name: verify_dev_env
          trigger: manual
          script:
            - apt-get update && apt-get install git -y
            - git clone https://$GITLAB_CI_CD_SCRIPT_USERNAME:$GITLAB_CI_CD_SCRIPT_PASSWORD@gitlab.com/infra-group/logicwind/general/gitlab-ci-cd-scripts.git
            - cp -r ./gitlab-ci-cd-scripts/frontend/* ./
            - chmod u+x verify-env-ci-cd-script.sh
            - echo $DEV_ENV_FILE | tr -s "###" "\n" | awk '{print "export " $1}' >> $GENERATED_ENV_FILE_NAME
            - bash verify-env-ci-cd-script.sh $GENERATED_ENV_FILE_NAME $ENV_SAMPLE_FILE_NAME
            - rm $GENERATED_ENV_FILE_NAME

      - step:
          name: deploy_dev
          trigger: manual
          image: node:19.9.0
          script:
            - export CI=false
            - echo "$DEV_ENV_FILE" | tr -s "###" "\n" | awk '{print "export " $1}' >> "$GENERATED_ENV_FILE_NAME"
            - source "$GENERATED_ENV_FILE_NAME"
            - npm install
            - npm run build
            - echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-service-account.json
            - export GOOGLE_APPLICATION_CREDENTIALS="$BITBUCKET_CLONE_DIR/firebase-service-account.json"
            - npm install -g firebase-tools
            - npx firebase deploy --only hosting:react-graphql-boilerplate --project "dev"
            - rm -rf build/